spring:
  kafka:
#    bootstrap-servers: moum-b-65tv-100657996.kr.cdss.naverncp.com:9094,
#      moum-b-65tw-100657996.kr.cdss.naverncp.com:9094,
#      moum-b-65tx-100657996.kr.cdss.naverncp.com:9094
    bootstrap-servers: 10.0.3.6:9092,10.0.3.7:9092,10.0.3.8:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: chat-group

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - email
              - profile
            redirect-uri: http://dev.moum.bangdpool.com/login/oauth2/code/google
          kakao:
            client-id: ${kakao.client-id}
            client-secret: ${kakao.client-secret}
            admin-key: ${kakao.client-admin}
            redirect-uri: http://dev.moum.bangdpool.com/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: ${naver.client-id}
            client-secret: ${naver.client-secret}
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://dev.moum.bangdpool.com/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  application:
    name: moum

  config:
    import:
      - "file:${user.home}/config/ncp.properties"
      - "file:${user.home}/config/mail.properties"

  datasource:
    url: jdbc:mysql://db-pfr3l-kr.vpc-pub-cdb.ntruss.com/moum
    username: moum
    password: bitcamp123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      enabled: true
      location: ${user.home}/upload
      max-request-size: 30MB
      max-file-size: 10MB

#  web:
#    resources:
#      static-locations: file:src/main/resources/static/

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 180000

mybatis:
  mapper-locations:
  type-aliases-package:

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    moum.project: DEBUG

server:
  port: 80
  ssl:
    enabled: false
